ALTER TABLE balances
ADD COLUMN IF NOT EXISTS total_income NUMERIC(12, 2) NOT NULL DEFAULT 0;

ALTER TABLE balances
ADD COLUMN IF NOT EXISTS total_expense NUMERIC(12, 2) NOT NULL DEFAULT 0;

ALTER TABLE balances
ADD COLUMN IF NOT EXISTS debt_amount NUMERIC(12, 2) NOT NULL DEFAULT 0;

ALTER TABLE balances
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW();
